export interface QuestionOption {
  text: string
  isCorrect: boolean
  order: number
}

export interface ExamQuestion {
  question: string
  type: "MULTIPLE_CHOICE" | "TRUE_FALSE"
  order: number
  points: number
  options: QuestionOption[]
}

const mc = (order: number, question: string, options: [string, string, string, string], correctIndex: number): ExamQuestion => ({
  question,
  type: "MULTIPLE_CHOICE",
  order,
  points: 1,
  options: options.map((text, idx) => ({
    text,
    isCorrect: idx === correctIndex,
    order: idx + 1,
  })),
})

const tf = (order: number, question: string, isTrueCorrect: boolean): ExamQuestion => ({
  question,
  type: "TRUE_FALSE",
  order,
  points: 1,
  options: [
    { text: "True", isCorrect: isTrueCorrect, order: 1 },
    { text: "False", isCorrect: !isTrueCorrect, order: 2 },
  ],
})

// ==========================================
// 1. CFMS (FINANCIAL MANAGEMENT SERVICES)
// ==========================================

export const cfmsFinalQuestions: ExamQuestion[] = [
  mc(1, "Which financial statement reports a company's financial position at a specific point in time?", ["Income Statement", "Balance Sheet", "Statement of Cash Flows", "Statement of Retained Earnings"], 1),
  mc(2, "What does the Current Ratio measure?", ["Long-term solvency", "Operational profitability", "Short-term liquidity", "Asset turnover efficiency"], 2),
  mc(3, "Which of the following is considered a non-cash expense on the income statement?", ["Rent expense", "Depreciation", "Utility expense", "Wages"], 1),
  mc(4, "What is the primary formula for the basic accounting equation?", ["Assets = Liabilities - Equity", "Assets = Liabilities + Equity", "Equity = Assets + Liabilities", "Liabilities = Assets + Equity"], 1),
  mc(5, "In capital budgeting, what does Net Present Value (NPV) represent?", ["The total future undiscounted cash inflows", "The present value of cash inflows minus initial investment outlay", "The rate that equates NPV to zero", "The total accounting profit divided by investment cost"], 1),
  mc(6, "Which capital budgeting metric is the discount rate that makes the project's NPV equal to zero?", ["Internal Rate of Return (IRR)", "Profitability Index", "Payback Period", "Modified Accounting Return"], 0),
  mc(7, "Working capital is calculated as:", ["Total Assets minus Total Liabilities", "Cash plus Accounts Receivable", "Current Assets minus Current Liabilities", "Operating Income minus Operating Expenses"], 2),
  mc(8, "The Cash Conversion Cycle (CCC) measures:", ["The time needed to convert cash outflows for resources into cash inflows from sales", "The speed of paying accounts payable only", "The total annual volume of checks cleared", "The number of bank accounts maintained"], 0),
  mc(9, "Which inventory costing method assumes that the last units purchased are the first units sold?", ["FIFO (First-In, First-Out)", "LIFO (Last-In, First-Out)", "Weighted Average Cost", "Specific Identification"], 1),
  mc(10, "Which ratio evaluates how efficiently a company uses its assets to generate sales?", ["Current Ratio", "Total Asset Turnover", "Debt to Equity Ratio", "Return on Equity"], 1),
  tf(11, "A high Debt-to-Equity ratio indicates that a company relies heavily on debt financing rather than equity.", true),
  tf(12, "Sunk costs should always be included as relevant cash flows when evaluating a new capital project.", false),
  mc(13, "What does the Quick Ratio (Acid-Test Ratio) exclude from Current Assets?", ["Cash", "Marketable securities", "Inventory", "Accounts receivable"], 2),
  mc(14, "Which of the following is a component of the DuPont analysis model for Return on Equity (ROE)?", ["Net Profit Margin × Asset Turnover × Financial Leverage", "Gross Margin × Quick Ratio × Debt Ratio", "Operating Margin × Price-Earnings × Current Ratio", "EBITDA × Working Capital × Equity Multiplier"], 0),
  mc(15, "The Capital Asset Pricing Model (CAPM) is used to estimate the:", ["Cost of preferred stock", "Expected return on equity based on systematic risk", "Coupon rate on corporate debentures", "Yield on treasury bills"], 1),
  mc(16, "What does Beta (β) measure in modern portfolio theory?", ["Company-specific unsystematic risk", "Volatility of an asset relative to the entire market", "The dividend yield percentage", "The bond default probability"], 1),
  mc(17, "When market interest rates increase, the market price of existing fixed-rate bonds will:", ["Increase", "Decrease", "Remain unchanged", "Double"], 1),
  mc(18, "The Weighted Average Cost of Capital (WACC) represents:", ["The overall minimum rate of return required by all capital providers", "The statutory corporate income tax rate", "The maximum dividend payout ratio", "The annual cost of short-term bank overdrafts"], 0),
  mc(19, "A company with high Operating Leverage has:", ["A large proportion of fixed operating costs relative to variable costs", "A high proportion of long-term debt in its capital structure", "Only variable costs in its manufacturing process", "Low sensitivity of EBIT to revenue fluctuations"], 0),
  mc(20, "What is the break-even point in units formula?", ["Fixed Costs / Selling Price per Unit", "Fixed Costs / Unit Contribution Margin", "Variable Costs / Contribution Margin Ratio", "Total Revenue / Variable Costs per Unit"], 1),
  tf(21, "Contribution margin is calculated as Sales Revenue minus Total Variable Costs.", true),
  tf(22, "An adverse variance in a cost budget means actual expenses were lower than budgeted expenses.", false),
  mc(23, "Which method of depreciation allocates equal amounts of expense across each year of an asset's useful life?", ["Double-declining balance", "Units-of-production", "Straight-line", "Sum-of-the-years'-digits"], 2),
  mc(24, "What does Earnings Before Interest and Taxes (EBIT) measure?", ["Operating profit before financing costs and income tax", "Net cash flow from financing activities", "Gross profit minus manufacturing overhead", "Net income available to common stockholders"], 0),
  mc(25, "In accounts receivable management, what does '2/10, net 30' mean?", ["2% penalty if not paid in 10 days, full due in 30 days", "2% cash discount if paid within 10 days, full payment due in 30 days", "Pay 2% now, 10% in 30 days", "2 months interest-free credit on 10 accounts"], 1),
  mc(26, "Days Sales Outstanding (DSO) measures:", ["How quickly inventory is manufactured", "Average number of days to collect payment on credit sales", "Days between order placement and receipt of goods", "Number of days cash remains in reserve accounts"], 1),
  mc(27, "Which activity is categorized under Cash Flow from Investing Activities?", ["Issuance of common stock", "Payment of cash dividends", "Purchase of manufacturing equipment", "Collection of cash from customers"], 2),
  mc(28, "Which activity is categorized under Cash Flow from Financing Activities?", ["Repayment of bank borrowings", "Sale of marketable securities", "Payment of employee salaries", "Purchase of raw materials"], 0),
  mc(29, "Free Cash Flow (FCF) to the firm represents:", ["Cash remaining after paying operating expenses and capital expenditures", "Net income plus total assets", "Total cash balance in the bank ledger", "Revenue minus inventory costs"], 0),
  mc(30, "What is the primary goal of financial management in a corporation?", ["Maximizing total quarterly sales revenue", "Maximizing long-term shareholder wealth", "Minimizing total employee headcount", "Eliminating all debt obligations"], 1),
  tf(31, "The Payback Period method considers the time value of money in its standard calculation.", false),
  tf(32, "Annuity due cash flows occur at the beginning of each payment period.", true),
  mc(33, "If an investment offers an annual interest rate of 12% compounded monthly, the Effective Annual Rate (EAR) is:", ["Equal to 12%", "Slightly greater than 12%", "Slightly less than 12%", "Exactly 1%"], 1),
  mc(34, "The Gordon Growth Model values common stock by assuming dividends will:", ["Grow at a constant rate indefinitely", "Decline to zero after five years", "Remain identical every quarter", "Fluctuate with prime interest rates"], 0),
  mc(35, "What is agency risk in corporate governance?", ["The risk of credit agencies downgrading bond ratings", "Potential conflict of interest between managers and shareholders", "The danger of insurance agents miscalculating claims", "Government regulatory intervention risk"], 1),
  mc(36, "A flexible budget differs from a static budget because a flexible budget:", ["Is never revised after approval", "Adjusts for changes in actual volume or activity levels", "Only includes fixed overhead expenses", "Is used solely for tax compliance"], 1),
  mc(37, "Which financial ratio reflects how many times interest charges are covered by operating earnings?", ["Times Interest Earned (Interest Coverage Ratio)", "Debt Ratio", "Operating Margin Ratio", "Quick Ratio"], 0),
  mc(38, "Capital rationing occurs when a firm:", ["Has unlimited funds to accept all positive NPV projects", "Has a budget constraint limiting investment in positive NPV projects", "Distributes all cash reserves as dividends", "Refuses to borrow from commercial banks"], 1),
  mc(39, "Which of the following is considered an unsystematic (diversifiable) risk?", ["A nationwide increase in corporate tax rates", "An unexpected labor strike at a specific manufacturing plant", "A sudden spike in national inflation", "A global recession impacting consumer demand"], 1),
  mc(40, "Modigliani and Miller Proposition I (without taxes) asserts that:", ["Capital structure directly determines firm value", "The value of a firm is independent of its capital structure", "Debt financing is always preferable to equity", "Firms should never issue preferred shares"], 1),
  tf(41, "The interest expense on corporate debt is typically tax-deductible, creating a debt tax shield.", true),
  tf(42, "Market capitalization equals the total book value of assets minus liabilities on the balance sheet.", false),
  mc(43, "What does the Price-to-Earnings (P/E) ratio indicate to investors?", ["The amount investors are willing to pay per dollar of current earnings", "The percentage of earnings paid out as dividends", "The total book value per common share", "The operating efficiency of fixed assets"], 0),
  mc(44, "Which derivative instrument gives the holder the right, but not the obligation, to buy an underlying asset?", ["Call Option", "Put Option", "Futures Contract", "Interest Rate Swap"], 0),
  mc(45, "A hedge is a financial strategy designed to:", ["Maximize speculative trading profits", "Reduce or offset the risk of adverse price movements", "Eliminate all corporate income tax liabilities", "Artificially inflate quarterly operating income"], 1),
  mc(46, "What is the primary role of an internal auditor in financial governance?", ["To prepare daily marketing campaigns", "To evaluate internal controls, risk management, and compliance", "To negotiate supplier purchase discounts", "To sign off on customer invoices"], 1),
  mc(47, "Which type of lease is recorded on the balance sheet as an asset and corresponding liability under IFRS 16?", ["Operating Lease and Finance Lease both", "Only Month-to-Month Rental Agreements", "Only Discretionary Short-term Leases", "No lease is ever capitalized"], 0),
  mc(48, "The Dividend Payout Ratio measures:", ["Dividends per share divided by stock price", "Total dividends paid divided by net income", "Operating cash flow divided by common dividends", "Retained earnings divided by net revenue"], 1),
  mc(49, "Economic Value Added (EVA) is calculated as:", ["Net Operating Profit After Tax (NOPAT) minus Cost of Capital Employed", "Total Revenue minus Total Operating Expenses", "Net Income minus Preferred Dividends", "EBITDA divided by Total Shareholder Equity"], 0),
  mc(50, "What is the zero-based budgeting (ZBB) approach?", ["Rolling previous year budgets with an inflation percentage", "Requiring every expenditure to be justified from a zero baseline each period", "Allocating funds based purely on historical seniority", "Restricting all departments to zero overhead spending"], 1),
  tf(51, "Commercial paper is an unsecured, short-term debt instrument issued by creditworthy corporations.", true),
  tf(52, "In financial modeling, sensitivity analysis tests the impact of changing multiple variables simultaneously.", false),
  mc(53, "The secondary financial market is where:", ["New securities are first offered to the public (IPO)", "Previously issued securities are traded between investors", "Only government treasury bills are auctioned", "Commercial banks obtain overnight central bank loans"], 1),
  mc(54, "Which ratio evaluates the dollar amount of sales generated per dollar invested in fixed assets?", ["Fixed Asset Turnover", "Current Asset Turnover", "Inventory Velocity Ratio", "Gross Profit Margin"], 0),
  mc(55, "Factoring refers to:", ["Selling accounts receivable to a third party at a discount for immediate cash", "Borrowing against raw material inventory", "Refinancing mortgage debt with lower interest", "Auditing factory machinery depreciation"], 0),
  mc(56, "What is the yield to maturity (YTM) of a bond?", ["The coupon payment divided by face value", "The total anticipated annual return if the bond is held until maturity", "The penalty rate for early bond redemption", "The risk-free rate published by the central bank"], 1),
  mc(57, "If a company has a negative working capital, it means:", ["Current liabilities exceed current assets", "Current assets exceed current liabilities", "Long-term debt exceeds total equity", "Net income is negative for the quarter"], 0),
  mc(58, "What is the primary purpose of a cash budget?", ["To forecast cash inflows and outflows to anticipate liquidity surpluses or deficits", "To calculate annual corporate income tax liabilities", "To determine employee bonus allocations", "To replace the official audited balance sheet"], 0),
  mc(59, "The DuPont framework decomposes Return on Assets (ROA) into:", ["Net Profit Margin × Total Asset Turnover", "Gross Margin × Quick Ratio", "Operating Margin × Debt Multiplier", "Current Ratio × Inventory Turnover"], 0),
  mc(60, "Under Philippine financial reporting guidelines, publicly accountable financial entities must adhere to:", ["PFRS (Philippine Financial Reporting Standards)", "US GAAP strictly without local adaptation", "Internal Company Guidelines only", "Cash Basis Accounting exclusively"], 0),
]

export const cfmsPracticeQuestions: ExamQuestion[] = [
  mc(1, "Which statement reflects cash receipts and disbursements over a reporting period?", ["Balance Sheet", "Income Statement", "Statement of Cash Flows", "Statement of Equity"], 2),
  mc(2, "If Current Assets are ₱500,000 and Current Liabilities are ₱250,000, what is the Current Ratio?", ["1.5", "2.0", "0.5", "2.5"], 1),
  mc(3, "Which of the following is considered an asset?", ["Accounts Payable", "Accounts Receivable", "Accrued Wages", "Unearned Revenue"], 1),
  mc(4, "Depreciation is categorized on the statement of cash flows as an adjustment that is:", ["Added back to Net Income in operating activities", "Subtracted from Net Income in financing activities", "Ignored as it has no tax impact", "Included in cash flows from investing activities"], 0),
  mc(5, "A project has an initial cost of ₱100,000 and returns ₱25,000 annually. What is its payback period?", ["3 years", "4 years", "5 years", "2.5 years"], 1),
  tf(6, "A project with a positive Net Present Value (NPV) is expected to add value to the firm.", true),
  tf(7, "Liquidity refers to how quickly an asset can be converted into cash without significant loss of value.", true),
  mc(8, "Which of the following costs does NOT change with changes in production volume within the relevant range?", ["Direct materials", "Factory lease rent", "Sales commission", "Packaging supplies"], 1),
  mc(9, "What happens to the break-even point if selling price per unit increases while variable and fixed costs remain constant?", ["Break-even point increases", "Break-even point decreases", "Break-even point remains unchanged", "Break-even point becomes zero immediately"], 1),
  mc(10, "Working capital equals:", ["Total Assets - Total Debt", "Current Assets - Current Liabilities", "Cash - Accounts Payable", "Revenue - Expenses"], 1),
  mc(11, "Which ratio evaluates profitability relative to total sales revenue?", ["Debt Ratio", "Net Profit Margin", "Current Ratio", "Asset Turnover"], 1),
  mc(12, "In financial math, the concept that a peso today is worth more than a peso in the future is known as:", ["Opportunity Cost", "Time Value of Money", "Purchasing Power Parity", "Capital Rationing"], 1),
  tf(13, "Variable costs per unit decrease as production volume increases.", false),
  tf(14, "The Quick Ratio includes inventory in its numerator calculation.", false),
  mc(15, "Which ratio is calculated as Net Income divided by Total Shareholders' Equity?", ["Return on Equity (ROE)", "Return on Assets (ROA)", "Gross Margin", "Debt-to-Equity Ratio"], 0),
  mc(16, "What is a budget variance?", ["The difference between actual financial performance and budgeted figures", "The fee charged by accounting software", "The total income tax owed to BIR", "The interest paid to commercial lenders"], 0),
  mc(17, "If actual expenses exceed budgeted expenses, the variance is described as:", ["Favorable", "Unfavorable (Adverse)", "Neutral", "Provisional"], 1),
  mc(18, "Which inventory method results in higher ending inventory value during periods of rising prices?", ["FIFO", "LIFO", "Average Cost", "Specific Identification"], 0),
  mc(19, "A company's capital structure consists of:", ["Only short-term trade credit", "Its mix of long-term debt and equity financing", "Its physical factory buildings and land", "Its executive management hierarchy"], 1),
  mc(20, "What is the primary document used to track anticipated daily or weekly cash flows?", ["Cash Budget", "Balance Sheet", "Depreciation Schedule", "Tax Return"], 0),
  tf(21, "Retained earnings represent cumulative net income that has not been distributed as dividends.", true),
  tf(22, "An adverse revenue variance means actual sales were higher than projected sales.", false),
  mc(23, "Which of the following is considered a current liability?", ["Accounts Payable", "Patents", "Equipment", "Common Stock"], 0),
  mc(24, "Gross Profit is calculated as:", ["Net Sales minus Cost of Goods Sold (COGS)", "EBIT minus Tax Expense", "Operating Income minus Interest", "Total Assets minus Liabilities"], 0),
  mc(25, "Operating Income is also commonly referred to as:", ["Net Income", "EBIT (Earnings Before Interest and Taxes)", "Gross Margin", "Retained Earnings"], 1),
  mc(26, "The Cost of Goods Sold includes:", ["Administrative executive salaries", "Direct materials, direct labor, and manufacturing overhead", "Marketing and advertising expenses", "Corporate income taxes"], 1),
  mc(27, "An investment of ₱10,000 earns 10% simple interest annually for 3 years. Total interest earned is:", ["₱1,000", "₱3,000", "₱3,310", "₱2,500"], 1),
  mc(28, "What does solvency refer to?", ["Ability to pay short-term obligations within 30 days", "Ability to meet long-term financial commitments and survive indefinitely", "Speed of collecting invoices from customers", "Daily cash in the bank register"], 1),
  tf(29, "Accounts Receivable represents money owed to the company by its customers for credit sales.", true),
  mc(30, "Which financial metric divides Operating Cash Flow by Total Debt to check debt servicing capacity?", ["Operating Cash Flow Ratio", "Inventory Turnover", "Current Ratio", "Gross Margin"], 0),
]

// ==========================================
// 2. CMMS (MARKETING MANAGEMENT SERVICES)
// ==========================================

export const cmmsFinalQuestions: ExamQuestion[] = [
  mc(1, "The traditional Marketing Mix is comprised of the 4 Ps, which stand for:", ["People, Process, Profit, Product", "Product, Price, Place, Promotion", "Plan, Positioning, Packaging, Promotion", "Publicity, Pricing, Placement, Production"], 1),
  mc(2, "In the extended 7 Ps framework for services marketing, the three additional elements are:", ["Packaging, Partnerships, Performance", "People, Process, Physical Evidence", "Perception, Positioning, Persuasion", "Profit, Publicity, Procurement"], 1),
  mc(3, "The STP marketing framework stands for:", ["Sales, Tactics, Promotion", "Segmentation, Targeting, Positioning", "Strategy, Timeline, Production", "Sourcing, Trading, Pricing"], 1),
  mc(4, "Dividing a broad consumer market into subsets based on personality, lifestyle, and values is known as:", ["Demographic segmentation", "Psychographic segmentation", "Geographic segmentation", "Behavioral segmentation"], 1),
  mc(5, "In a SWOT analysis, internal strategic factors are:", ["Strengths and Weaknesses", "Opportunities and Threats", "Strengths and Threats", "Weaknesses and Opportunities"], 0),
  mc(6, "What is a Unique Selling Proposition (USP)?", ["The lowest discount price offered during a sale", "The distinctive factor that differentiates a product from its competitors", "The total sales quota assigned to regional teams", "The packaging legal disclosure label"], 1),
  mc(7, "The four successive stages of the standard Product Life Cycle (PLC) are:", ["Inception, Growth, Saturation, Death", "Introduction, Growth, Maturity, Decline", "Development, Testing, Distribution, Review", "Research, Launch, Peak, Rebrand"], 1),
  mc(8, "Price Skimming is a pricing strategy that involves:", ["Setting a very low price to gain rapid market share", "Setting a high initial price and lowering it gradually over time", "Pricing products based exactly on competitor averages", "Selling products below cost to drive rivals out of business"], 1),
  mc(9, "Penetration Pricing is most effective when:", ["Market demand is highly price elastic and significant economies of scale exist", "The product is a luxury item with low volume", "There is zero existing competition in the category", "The brand seeks an elite exclusive status"], 0),
  mc(10, "What does Search Engine Optimization (SEO) aim to achieve?", ["Purchasing paid sponsored ads on search engine result pages", "Improving organic website ranking on search engines through relevant content and technical optimization", "Sending unsolicited automated promotional emails", "Tracking user social media profiles without cookies"], 1),
  tf(11, "Brand Equity refers to the commercial value derived from consumer perception of a brand name rather than the product itself.", true),
  tf(12, "In consumer behavior, cognitive dissonance occurs when a buyer feels completely satisfied without any post-purchase doubt.", false),
  mc(13, "What is Customer Lifetime Value (CLV)?", ["The total gross revenue earned in a single sales transaction", "The predicted total net profit attributable to the entire future relationship with a customer", "The customer's annual income level", "The duration of the company's trademark patent"], 1),
  mc(14, "Customer Acquisition Cost (CAC) is calculated by dividing:", ["Total marketing and sales expenses by number of new customers acquired", "Total revenue by total customers", "Cost of goods sold by repeat buyers", "Advertising budget by employee payroll"], 0),
  mc(15, "In digital marketing analytics, Click-Through Rate (CTR) is calculated as:", ["Total clicks divided by total impressions multiplied by 100", "Total conversions divided by clicks", "Total pageviews divided by bounce rate", "Total purchases divided by ad budget"], 0),
  mc(16, "What does Net Promoter Score (NPS) evaluate?", ["Employee job satisfaction levels", "Customer loyalty and likelihood of recommending a company to others", "Quarterly sales revenue growth", "Social media hashtag popularity"], 1),
  mc(17, "Which distribution strategy places products in as many retail outlets as possible?", ["Exclusive distribution", "Selective distribution", "Intensive distribution", "Direct franchising"], 2),
  mc(18, "A luxury watchmaker selling exclusively through two boutique stores per major city is using:", ["Intensive distribution", "Exclusive or Selective distribution", "Mass merchandising", "Wholesale dumping"], 1),
  mc(19, "In consumer behavior, the first stage of the Buyer Decision Process is:", ["Evaluation of alternatives", "Need or Problem recognition", "Information search", "Post-purchase evaluation"], 1),
  mc(20, "What is the primary role of Integrated Marketing Communications (IMC)?", ["Ensuring all promotional tools and messaging deliver a unified, consistent brand message", "Eliminating all marketing channels except digital social media", "Focusing solely on public relations press releases", "Separating advertising budgets into independent silos"], 0),
  tf(21, "Direct marketing allows companies to communicate directly with targeted individual consumers without intermediaries.", true),
  tf(22, "A perceptual map visually displays consumer perceptions of competing brands along key attribute dimensions.", true),
  mc(23, "Which metric measures the percentage of visitors who navigate away from a website after viewing only one page?", ["Conversion Rate", "Bounce Rate", "Churn Rate", "Impression Share"], 1),
  mc(24, "What is A/B testing in marketing?", ["Testing two marketing variants against each other to identify which performs better with audiences", "Testing product durability under laboratory stress", "Comparing audit scores of two accounting agencies", "Interviewing applicants from Group A and Group B"], 0),
  mc(25, "In the BCG Growth-Share Matrix, a business unit with high market share in a slow-growth industry is a:", ["Star", "Cash Cow", "Question Mark", "Dog"], 1),
  mc(26, "In the BCG Matrix, a business unit with low market share in a high-growth market is classified as a:", ["Star", "Cash Cow", "Question Mark (Problem Child)", "Dog"], 2),
  mc(27, "What is the primary purpose of a brand positioning statement?", ["To outline the company's tax depreciation strategy", "To articulate how a brand uniquely solves a target customer's problem better than alternatives", "To register corporate trademarks with government authorities", "To list the retail pricing of all catalog items"], 1),
  mc(28, "Content marketing focuses on:", ["Creating and distributing valuable, relevant, and consistent content to attract and retain an audience", "Bombarding consumers with aggressive pop-up advertisements", "Cold-calling telephone prospects during evening hours", "Purchasing commercial billboard space exclusively"], 0),
  mc(29, "Which metric calculates the percentage of customers who cease using a company's product or service over a specific period?", ["Retention Rate", "Churn Rate", "Click Rate", "Adherence Rate"], 1),
  mc(30, "What does Porter's Five Forces model assess?", ["Employee turnover and labor disputes", "Industry attractiveness and competitive intensity", "Corporate social responsibility contributions", "International currency exchange volatility"], 1),
  tf(31, "Public Relations (PR) primarily focuses on creating non-paid positive media coverage and managing public perception.", true),
  tf(32, "Push marketing strategies focus on inducing ultimate consumers to demand products from retailers.", false),
  mc(33, "A Pull marketing strategy directs promotional efforts toward:", ["Final consumers to build demand and pull the product through the distribution channel", "Wholesalers and trade distributors to stock products", "Company shareholders exclusively", "Raw material manufacturing suppliers"], 0),
  mc(34, "Which pricing strategy involves pricing products at ₱99.95 instead of ₱100.00?", ["Psychological pricing (Odd pricing)", "Cost-plus pricing", "Prestige pricing", "Dynamic surging"], 0),
  mc(35, "What is secondary market research data?", ["Data gathered firsthand specifically for the project at hand", "Information that already exists having been collected previously for another purpose", "Data from secondary school consumer focus groups", "Classified competitor data obtained via corporate espionage"], 1),
  mc(36, "A focus group in qualitative market research typically consists of:", ["100 to 500 online survey respondents", "6 to 10 prescreened participants guided by a moderator to discuss a product or topic", "A one-on-one audit interview with a CEO", "Secret shoppers observing store checkout lanes"], 1),
  mc(37, "Which term describes when sales of a new company product cannibalize the sales of its existing products?", ["Market Cannibalization", "Brand Dilution", "Channel Encroachment", "Market Saturation"], 0),
  mc(38, "Omnichannel marketing refers to:", ["Selling through television infomercials only", "Providing a seamless, integrated customer shopping experience across online and physical channels", "Establishing retail stores in every province simultaneously", "Running advertisements on all radio stations"], 1),
  mc(39, "What is Maslow's highest level in the hierarchy of human needs?", ["Safety needs", "Social belongingness needs", "Self-actualization", "Physiological needs"], 2),
  mc(40, "Which ethical issue involves falsely conveying that a company's products are environmentally friendly?", ["Bait and switch", "Greenwashing", "Astroturfing", "Predatory dumping"], 1),
  tf(41, "Co-branding is a marketing partnership where two distinct brand names appear together on a single product.", true),
  tf(42, "Social proof in marketing refers to the psychological tendency for consumers to follow the actions and reviews of others.", true),
  mc(43, "What does Key Performance Indicator (KPI) mean in marketing management?", ["A quantifiable measure used to evaluate success in reaching operational and strategic goals", "The primary key identifying consumer demographic profiles in a database", "The minimum pricing threshold permitted by regulatory bodies", "The statutory consumer warranty registration number"], 0),
  mc(44, "Which type of advertising is aimed at stimulating overall demand for an entire generic product category rather than a specific brand?", ["Pioneering (Informative/Primary demand) advertising", "Comparative advertising", "Reminder advertising", "Institutional advocacy"], 0),
  mc(45, "In digital marketing, what does programmatic advertising refer to?", ["Manual negotiations of banner placements between publishers and media buyers", "Automated buying and selling of digital advertising inventory in real-time via algorithms", "Advertising specifically designed for computer programming software", "Traditional newspaper classified listings"], 1),
  mc(46, "What is remarketing (retargeting)?", ["Serving digital ads specifically to users who have previously visited your website or app", "Rebranding an old product with a new logo", "Recalling defective products from retail stores", "Discounting out-of-season inventory at clearance outlets"], 0),
  mc(47, "Which formula determines Return on Marketing Investment (ROMI)?", ["(Revenue from Marketing - Marketing Cost) / Marketing Cost × 100", "Total Sales / Total Assets", "Net Profit / Total Equity", "Marketing Expenses / Employee Headcount"], 0),
  mc(48, "What is influencer marketing?", ["Engaging individuals with dedicated social followings and credibility to endorse products", "Using television news anchors to endorse candidates", "Lobbying government politicians to change trade policies", "Distributing promotional flyers to pedestrians on street corners"], 0),
  mc(49, "A company launching a product line extension introduces:", ["An entirely new brand in an unrelated market", "Additional items in an existing product category under the same brand name (e.g. new flavors or sizes)", "A competitor's product packaged in white boxes", "A non-profit charitable donation initiative"], 1),
  mc(50, "What is market penetration?", ["Entering a new geographic continent with an experimental product line", "Increasing sales of existing products to existing market segments", "Liquidating slow-moving stock at scrap value", "Acquiring a controlling stake in a competitor's supplier"], 1),
  tf(51, "Cost-plus pricing calculates selling price by adding a specified markup percentage to total product unit costs.", true),
  tf(52, "In digital advertising, Cost Per Mille (CPM) refers to the advertising cost per one million page views.", false),
  mc(53, "In advertising terms, 'CPM' stands for Cost Per Mille, which measures the price of:", ["1,000 advertisement impressions", "1,000,000 ad clicks", "100 confirmed orders", "1 single high-profile television commercial"], 0),
  mc(54, "Which stage of the consumer adoption curve represents the first 2.5% of consumers who adopt an innovative product?", ["Innovators", "Early Adopters", "Early Majority", "Laggards"], 0),
  mc(55, "What is ambush marketing?", ["Advertising directly inside rival retail store aisles", "Associating a brand with a major event without paying official sponsorship fees", "Hiding subliminal messages in audio broadcasts", "Running aggressive television ads during late-night hours"], 1),
  mc(56, "The practice of adapting marketing strategies and products to individual local markets across different countries is called:", ["Global Standardization", "Glocalization (Localization)", "Market Saturation", "Tariff Dumping"], 1),
  mc(57, "Which customer relationship management (CRM) tool helps forecast upcoming deals and sales pipelines?", ["Lead Tracking and Opportunity Management", "Factory Maintenance Scheduler", "Payroll Deduction Calculator", "Tax Depreciation Engine"], 0),
  mc(58, "What does 'earned media' represent in the modern media mix?", ["Paid search advertisements and television commercials", "Company-owned websites, blogs, and social channels", "Unpaid brand publicity gained through word-of-mouth, press coverage, reviews, and social shares", "Billboards installed on company properties"], 2),
  mc(59, "What is a loss-leader pricing strategy?", ["Selling a selected product at a loss or minimal margin to attract shoppers who will buy other profitable items", "Charging consumers extra fees for basic packaging", "Selling damaged stock at salvage auctions", "Abandoning an entire product line due to declining sales"], 0),
  mc(60, "The Data Privacy Act of 2012 (Republic Act 10173) in the Philippines requires marketers to:", ["Protect personal customer data and obtain informed consent prior to data collection and processing", "Never use digital marketing communications in business", "Disclose all proprietary corporate secrets on their public website", "Store customer email addresses in unencrypted public spreadsheets"], 0),
]

export const cmmsPracticeQuestions: ExamQuestion[] = [
  mc(1, "The 4 Ps of marketing are Product, Price, Place, and:", ["People", "Promotion", "Process", "Profit"], 1),
  mc(2, "Market segmentation divides a market based on common characteristics such as demographics, geography, or:", ["Psychographics and behavior", "Supplier production capacity", "Internal corporate culture", "Accounting tax bracket"], 0),
  mc(3, "In a SWOT analysis, external factors are represented by:", ["Strengths and Weaknesses", "Opportunities and Threats", "Strengths and Opportunities", "Weaknesses and Threats"], 1),
  mc(4, "What does SEO stand for in modern marketing?", ["Search Engine Optimization", "Social Engagement Operation", "Sales Executive Outlook", "System Error Overview"], 0),
  mc(5, "Which pricing strategy involves setting an initial low price to quickly attract a large volume of customers?", ["Penetration pricing", "Price skimming", "Prestige pricing", "Cost-plus pricing"], 0),
  tf(6, "A target market is a specific group of consumers toward whom a company directs its marketing efforts.", true),
  tf(7, "Word-of-mouth marketing is considered an example of paid advertising.", false),
  mc(8, "Which metric measures the percentage of people who see an ad and click on it?", ["Click-Through Rate (CTR)", "Cost Per Lead", "Bounce Rate", "Conversion Time"], 0),
  mc(9, "Brand identity includes visual elements such as:", ["Logos, typography, color schemes, and packaging", "Internal payroll spreadsheets", "Warehouse inventory shelves", "Corporate bank routing numbers"], 0),
  mc(10, "In the Product Life Cycle, which stage is characterized by peak sales and intense competition?", ["Introduction", "Growth", "Maturity", "Decline"], 2),
  mc(11, "What is the primary objective of Content Marketing?", ["To provide valuable, engaging information to attract and retain target customers", "To aggressively hard-sell products via cold telephone calls", "To reduce raw material costs in factories", "To bypass digital privacy regulations"], 0),
  mc(12, "Customer Retention Rate measures:", ["The percentage of customers a business keeps over a specific period", "How many new leads visit a retail store", "How quickly customer complaints are escalated", "The average price paid per transaction"], 0),
  tf(13, "Primary research involves analyzing data that was already gathered by government census agencies.", false),
  tf(14, "Demographic segmentation classifies audiences by measurable traits such as age, gender, and income.", true),
  mc(15, "What is a Call-to-Action (CTA) in marketing copy?", ["An instruction to the audience designed to provoke an immediate response (e.g., 'Buy Now', 'Subscribe Today')", "A mandatory government legal notice", "A telephone conference between sales managers", "An announcement of company bankruptcy"], 0),
  mc(16, "Which tool evaluates customer brand sentiment and loyalty with a single score from -100 to +100?", ["Net Promoter Score (NPS)", "Inventory Turnover", "Gross Margin Index", "Quick Ratio"], 0),
  mc(17, "When two products are sold together as a single combined package at a discounted rate, this is called:", ["Price bundling", "Price skimming", "Odd pricing", "Dynamic pricing"], 0),
  mc(18, "Which digital marketing channel typically boasts the highest direct return on investment for retention campaigns?", ["Email Marketing", "Print Magazine classifieds", "Transit billboard posters", "Direct fax broadcasts"], 0),
  mc(19, "A Buyer Persona is best described as:", ["A semi-fictional representation of an ideal customer based on real data and market research", "A real celebrity hired to do product endorsements", "The company's top-performing sales representative", "An undercover competitor mystery shopper"], 0),
  mc(20, "What is the main purpose of A/B testing on a website landing page?", ["To compare two design variations to determine which yields higher conversions", "To test website load speeds under extreme power surges", "To check employee typing accuracy", "To create backup copies of customer databases"], 0),
  tf(21, "Direct-to-Consumer (D2C) brands sell their products directly to end customers without retail intermediaries.", true),
  tf(22, "A brand's positioning statement is written primarily for competitors to read.", false),
  mc(23, "Which of the following is considered an outbound marketing tactic?", ["Cold calling and TV commercials", "Search Engine Optimization blog posts", "Opt-in educational newsletters", "Podcast guest interviews"], 0),
  mc(24, "What does the acronym CRM stand for in business software?", ["Customer Relationship Management", "Consumer Resource Marketing", "Centralized Retail Merchandise", "Corporate Revenue Metrics"], 0),
  mc(25, "In advertising, Reach refers to:", ["The total number of unique individuals exposed to a media campaign", "The physical distance between retail stores", "The height of roadside billboard signs", "The total number of times an ad was clicked"], 0),
  mc(26, "Frequency in media planning refers to:", ["The average number of times an individual is exposed to an advertisement", "How fast radio waves travel", "The number of days between product launches", "The speed of online checkout servers"], 0),
  mc(27, "Which promotional strategy offers temporary incentives like coupons, contests, or rebates to boost immediate sales?", ["Sales Promotion", "Personal Selling", "Corporate Philanthropy", "Brand Licensing"], 0),
  mc(28, "Social proof in marketing is commonly demonstrated through:", ["Customer testimonials, ratings, reviews, and client logos", "Internal audit memos", "Confidential supplier contracts", "Government patent certificates"], 0),
  tf(29, "Viral marketing relies on rapid, organic sharing of content between individuals across social networks.", true),
  mc(30, "What is the primary role of packaging in product strategy?", ["To protect the product, provide information, and enhance brand appeal at the point of sale", "To add unnecessary weight to increase shipping fees", "To hide expiration dates from retail clerks", "To conceal manufacturer details from the public"], 0),
]

// ==========================================
// 3. COMS (OPERATIONS MANAGEMENT SERVICES)
// ==========================================

export const comsFinalQuestions: ExamQuestion[] = [
  mc(1, "Operations management is primarily concerned with:", ["Planning, organizing, and supervising the production of goods and delivery of services", "Managing corporate tax planning and stock repurchases", "Negotiating collective bargaining agreements with trade unions", "Designing executive promotional advertising campaigns"], 0),
  mc(2, "Which management philosophy emphasizes continuous improvement across all organizational processes?", ["Total Quality Management (TQM)", "Bureaucratic Management", "Classical Scientific Management", "Contingency Administration"], 0),
  mc(3, "In Lean Manufacturing, the Japanese term 'Kaizen' translates to:", ["Continuous improvement for the better", "Wasteful overproduction", "Just-In-Time delivery", "Poka-Yoke error proofing"], 0),
  mc(4, "The 5S methodology originates from Japanese manufacturing and consists of Sort, Set in Order, Shine, Standardize, and:", ["Sustain", "Simplify", "Speed", "Strategize"], 0),
  mc(5, "Six Sigma quality methodologies aim for a defect rate of no more than:", ["3.4 defects per million opportunities", "34 defects per thousand opportunities", "3.4 defects per hundred items", "0 defects under all conditions"], 0),
  mc(6, "The standard Five-Phase cycle used in Six Sigma projects is:", ["DMAIC (Define, Measure, Analyze, Improve, Control)", "PDCA (Plan, Do, Check, Act)", "PERT (Program Evaluation Review Technique)", "CPM (Critical Path Method)"], 0),
  mc(7, "In inventory control, the Economic Order Quantity (EOQ) model balances:", ["Holding costs and ordering (setup) costs", "Labor expenses and shipping surcharges", "Sales discounts and bad debts", "Raw material price and inflation index"], 0),
  mc(8, "What does the Just-In-Time (JIT) production system aim to minimize?", ["Excess inventory and waste", "Employee wages", "Customer feedback forms", "Machinery maintenance schedules"], 0),
  mc(9, "In project management, the Critical Path is defined as:", ["The sequence of dependent tasks that takes the longest time to complete, determining minimum project duration", "The path with the highest financial budget allocation", "The shortest route on a factory floor map", "The tasks that can be delayed indefinitely without consequence"], 0),
  mc(10, "A Gantt chart is a project management tool used primarily for:", ["Tracking activity schedules, dependencies, and progress over time", "Calculating employee income tax withholdings", "Visualizing factory electrical wiring diagrams", "Auditing supplier income statements"], 0),
  tf(11, "In the Theory of Constraints (TOC), the bottleneck is the operation with the lowest capacity that restricts total throughput.", true),
  tf(12, "Slack time in a project network represents the amount of time a task can be delayed without delaying the project finish date.", true),
  mc(13, "What does the Bullwhip Effect in supply chain management describe?", ["Increasing fluctuations in inventory demand as one moves further up the supply chain from retailer to raw supplier", "The physical punishment of factory workers for missing targets", "Sudden transport rate hikes during port congestion", "The rapid drop in consumer retail purchasing during holidays"], 0),
  mc(14, "Which tool uses the 80/20 rule to identify the vital few defects causing the majority of problems?", ["Pareto Chart", "Scatter Diagram", "Control Chart", "Flowchart"], 0),
  mc(15, "A Fishbone Diagram (Ishikawa Diagram) is used in quality control to:", ["Identify and analyze root causes of a specific problem or defect", "Measure assembly line electrical consumption", "Forecast future quarterly product demand", "Calculate safety stock levels for warehouses"], 0),
  mc(16, "What is Poka-Yoke in Japanese operational design?", ["Mistake-proofing (fool-proofing) mechanisms to prevent human errors", "An annual bonus celebration for factory workers", "A technique for negotiating supplier discounts", "A robotic assembly system for automobiles"], 0),
  mc(17, "In ABC Inventory Analysis, Category A items typically represent:", ["Roughly 15-20% of inventory items accounting for 70-80% of total inventory value", "Bulk low-value items like nuts and bolts", "Obsolete items awaiting scrap disposal", "Packaging supplies kept on retail display"], 0),
  mc(18, "Which inventory review system checks stock levels continuously and triggers an order whenever inventory hits the Reorder Point?", ["Continuous Review System (Fixed-Order-Quantity / Q-System)", "Periodic Review System (P-System)", "Visual Two-Bin System only", "Ad-hoc Seasonal Purchasing"], 0),
  mc(19, "Safety stock is held primarily to protect against:", ["Uncertainty in demand and supplier lead times", "Factory property tax increases", "Changes in executive management", "Routine office utility outages"], 0),
  mc(20, "What is Total Productive Maintenance (TPM)?", ["A holistic approach to equipment maintenance that strives for perfect production with zero breakdowns and zero defects", "Replacing all machinery every twelve months", "Outsourcing facility janitorial services to third parties", "Running machines continuously until total engine failure"], 0),
  tf(21, "Capacity utilization is calculated by dividing actual output by maximum design capacity.", true),
  tf(22, "In lean terminology, 'Muda' refers to value-adding activities in a manufacturing cell.", false),
  mc(23, "In Lean Manufacturing, the 7 traditional forms of waste (Muda) include Overproduction, Waiting, Transport, Inventory, Motion, Defects, and:", ["Over-processing (Inappropriate processing)", "High executive compensation", "Corporate income taxation", "Excessive customer communication"], 0),
  mc(24, "What does a Kanban card signal in a pull manufacturing system?", ["A visual authorization to produce or withdraw a specific quantity of parts", "A formal termination notice for defective workers", "A receipt for payment from retail store cashiers", "A government export customs clearance permit"], 0),
  mc(25, "Which process layout arranges machinery and workstations according to the progressive sequence of operations required to make a product?", ["Product (Assembly Line) Layout", "Process (Functional) Layout", "Fixed-Position Layout", "Cellular Layout"], 0),
  mc(26, "Building large ships, aircraft, or commercial bridges typically utilizes which facility layout?", ["Fixed-Position Layout", "Assembly Line Layout", "Continuous Flow Layout", "Retail Merchandising Layout"], 0),
  mc(27, "What is the primary objective of aggregate operations planning?", ["Matching intermediate-term supply and demand while minimizing total production and labor costs", "Scheduling daily 15-minute worker tea breaks", "Designing digital social media marketing campaigns", "Auditing historical balance sheet assets"], 0),
  mc(28, "In aggregate planning, a 'Chase Demand' strategy involves:", ["Adjusting production rates and workforce size to match fluctuating demand in each period", "Maintaining constant output and building inventory during slow periods", "Refusing customer orders during peak seasons", "Outsourcing all production overseas"], 0),
  mc(29, "What does Enterprise Resource Planning (ERP) software do?", ["Integrates core business processes (finance, HR, supply chain, manufacturing, procurement) into a unified database", "Designs 3D engineering blueprints for machinery", "Monitors employee social media activity during breaks", "Manages automated stock market trading algorithms"], 0),
  mc(30, "The International Organization for Standardization (ISO) 9001 standard specifies requirements for a:", ["Quality Management System (QMS)", "Food Safety Environmental Audit", "Information Security Framework", "Workplace Occupational Salary Scale"], 0),
  tf(31, "Lead time is the total latency between the initiation and completion of a production or procurement process.", true),
  tf(32, "Statistical Process Control (SPC) uses control charts to distinguish between common cause and special cause variations.", true),
  mc(33, "In Statistical Process Control, control limits on a Shewhart chart are typically set at:", ["±3 standard deviations (sigma) from the process centerline", "±1 standard deviation from the median", "±10 percentage points of product price", "Arbitrary points decided by line operators"], 0),
  mc(34, "The Cost of Quality is divided into four main categories: Prevention, Appraisal, Internal Failure, and:", ["External Failure Costs", "Marketing Budget Costs", "Shipping Freight Surcharges", "Depreciation Amortization"], 0),
  mc(35, "Costs incurred when defective products reach customers (e.g. warranty claims, recalls, legal liabilities) are:", ["External Failure Costs", "Internal Failure Costs", "Appraisal Costs", "Prevention Costs"], 0),
  mc(36, "Which tool provides a visual representation of all steps in a process from start to finish?", ["Process Map / Flowchart", "Gantt Matrix", "Control Histogram", "Scatter Diagram"], 0),
  mc(37, "In PERT analysis, the expected task duration is calculated using three estimates: Optimistic (a), Pessimistic (b), and:", ["Most Likely (m)", "Historical Average (h)", "Minimum Feasible (min)", "Theoretical Limit (t)"], 0),
  mc(38, "The formula for PERT expected task time (TE) is:", ["(a + 4m + b) / 6", "(a + m + b) / 3", "(2a + 2m + 2b) / 6", "(a + b) / 2"], 0),
  mc(39, "Crashing a project in project management refers to:", ["Shortening task durations by adding extra resources while balancing incremental costs", "Intentionally causing project cancellation due to insolvency", "Overwriting computer scheduling files with corrupt backups", "Skipping quality inspection checks to meet deadlines"], 0),
  mc(40, "What does Third-Party Logistics (3PL) refer to?", ["Outsourcing operational logistics, warehousing, and transportation to specialized external service providers", "Having retail customers pick up goods at maritime docks", "Internal staff driving company delivery trucks", "Government military transport convoys"], 0),
  tf(41, "Cross-docking is a logistics practice where incoming goods are directly transferred to outbound trucks with minimal or no storage time.", true),
  tf(42, "Vendor-Managed Inventory (VMI) requires the buyer to place manual purchase orders for every delivery.", false),
  mc(43, "In Vendor-Managed Inventory (VMI):", ["The supplier monitors the customer's inventory levels and handles restocking decisions directly", "The customer manages the supplier's factory machines", "Independent retail auditors dictate order sizes weekly", "Inventory is only paid for when fully consumed after one year"], 0),
  mc(44, "What is the Deming Cycle for continuous quality improvement?", ["Plan - Do - Check - Act (PDCA)", "Prepare - Deliver - Charge - Audit", "Produce - Distribute - Consume - Abandon", "Position - Drive - Calculate - Adjust"], 0),
  mc(45, "Which operations metric calculates the average percentage of manufacturing time that actually adds value to a product?", ["Process Velocity / Process Cycle Efficiency", "Total Factor Depreciation", "Equipment Footprint Ratio", "Payroll Utilization Factor"], 0),
  mc(46, "What is an Andon cord or light in a Lean production facility?", ["A visual signaling system that allows workers to halt the production line when a defect or safety issue occurs", "A security alarm detecting unauthorized visitors", "An automated clock chiming shift break times", "An emergency fire sprinkler trigger"], 0),
  mc(47, "Which facility location method uses a quantitative grid coordinate system weighted by transport volumes to find a central warehouse site?", ["Center-of-Gravity Method", "Factor Rating Method", "Locational Cost-Volume Analysis", "Transportation Simplex Method"], 0),
  mc(48, "Overall Equipment Effectiveness (OEE) measures manufacturing productivity by multiplying:", ["Availability × Performance × Quality", "Speed × Weight × Output", "Labor Hours × Machine Horsepower × Voltage", "Efficiency × Capacity × Price"], 0),
  mc(49, "Work-in-Process (WIP) refers to:", ["Partially finished goods awaiting further processing or assembly", "Unprocessed raw materials in outdoor shipping containers", "Packaged goods stored on retail showroom shelves", "Office stationery used by accounting personnel"], 0),
  mc(50, "What is reverse logistics?", ["The process of moving goods from their typical final destination for returns, repairs, recycling, or disposal", "Driving delivery trucks backwards into warehouse bays", "Shipping goods from factory to distributor", "Exporting goods to overseas territories"], 0),
  tf(51, "Preventive maintenance is performed before equipment failure occurs to preserve equipment condition and reduce unplanned downtime.", true),
  tf(52, "In lean operations, takt time is the rate at which products must be completed to satisfy customer demand rate.", true),
  mc(53, "Takt time is calculated as:", ["Available productive work time divided by customer demand volume", "Total factory square footage divided by machine count", "Total employee payroll divided by pieces produced", "Total delivery truck mileage divided by fuel volume"], 0),
  mc(54, "Which forecasting method uses opinions from an anonymous panel of industry experts across multiple iteration rounds?", ["Delphi Method", "Linear Regression", "Exponential Smoothing", "Weighted Moving Average"], 0),
  mc(55, "Which document specifies the raw materials, subassemblies, and quantities needed to manufacture an end product?", ["Bill of Materials (BOM)", "Purchase Order Requisition", "Income Statement Schedule", "Certificate of Origin"], 0),
  mc(56, "Material Requirements Planning (MRP) systems use inputs from the Bill of Materials, Inventory Master File, and:", ["Master Production Schedule (MPS)", "Corporate Tax Filing Sheet", "Customer Credit Scoring Report", "Social Media Analytics Dashboard"], 0),
  mc(57, "What is a bottleneck in an assembly line?", ["The point of congestion where process stage workload arrives faster than that stage can handle", "The drainage pipe in a factory chemical tank", "The storage bin holding spare machinery bolts", "The shipping dock security checkpoint gate"], 0),
  mc(58, "What does ergonomics in workplace operations focus on?", ["Designing workspaces and tools to fit human physiological capabilities and reduce injury or fatigue", "Calculating executive compensation stock packages", "Auditing financial statements for fraud", "Managing automated social media replies"], 0),
  mc(59, "ISO 14001 certification specifically sets standards for an organization's:", ["Environmental Management System", "Financial Accounting System", "Cybersecurity and Password Encryption", "Food Nutrition Content Verification"], 0),
  mc(60, "The Occupational Safety and Health Standards (OSHS) in the Philippines require employers to:", ["Ensure safe and healthful working conditions for workers and provide personal protective equipment (PPE) as needed", "Eliminate all breaks during 8-hour production shifts", "Disallow employee safety training seminars", "Charge workers for standard safety helmets and boots"], 0),
]

export const comsPracticeQuestions: ExamQuestion[] = [
  mc(1, "Operations management primarily focuses on:", ["Transforming resource inputs into finished goods and services", "Auditing quarterly shareholder balance sheets", "Designing marketing logos and television advertisements", "Managing corporate legal disputes"], 0),
  mc(2, "In Lean Manufacturing, eliminating waste and continuous improvement is known as:", ["Kaizen", "Kanban", "Poka-Yoke", "Heijunka"], 0),
  mc(3, "The 5S methodology is designed to create a workplace that is:", ["Organized, clean, standardized, and safe", "Heavily bureaucratic with paper checklists", "Filled with large buffer inventories", "Staffed exclusively by automated robotics"], 0),
  mc(4, "Which quality concept aims for near-perfection with only 3.4 defects per million opportunities?", ["Six Sigma", "ISO 9000", "Zero Margins", "Batch Calibration"], 0),
  mc(5, "In project management, a Gantt Chart is used to:", ["Schedule, visualize, and track project tasks against a timeline", "Calculate corporate income tax liabilities", "Draw mechanical equipment gear blueprints", "Manage employee payroll withholdings"], 0),
  tf(6, "The Critical Path in a project network determines the minimum time required to complete the entire project.", true),
  tf(7, "A bottleneck in a process is the step with the highest capacity.", false),
  mc(8, "The Economic Order Quantity (EOQ) formula calculates the optimal order size that minimizes:", ["Total ordering costs and holding costs", "Total employee wages and bonuses", "Advertising agency commissions", "Factory building lease rental"], 0),
  mc(9, "What does JIT stand for in modern operations management?", ["Just-In-Time", "Job-Integrated-Tasks", "Joint-Industrial-Trading", "Judged-Inventory-Throughput"], 0),
  mc(10, "In a supply chain, when small changes in retail sales create large fluctuations in wholesale orders, this is called the:", ["Bullwhip Effect", "Domino Principle", "Cascade Threshold", "Amplification Paradox"], 0),
  mc(11, "Which quality tool uses the 80/20 rule to prioritize which defects to fix first?", ["Pareto Chart", "Check Sheet", "Scatter Diagram", "Histogram"], 0),
  mc(12, "A Fishbone Diagram (Cause-and-Effect Diagram) helps teams:", ["Identify potential root causes of a problem or defect", "Measure assembly line electrical usage", "Draft company employment contracts", "Calculate quarterly depreciation"], 0),
  tf(13, "Poka-Yoke refers to mechanisms that prevent mistakes from happening during a process.", true),
  tf(14, "Safety stock is held to buffer against unexpected spikes in customer demand or supplier delays.", true),
  mc(15, "In ABC Inventory Analysis, which category contains the small percentage of items that account for the largest share of dollar value?", ["Category A", "Category B", "Category C", "Category D"], 0),
  mc(16, "A visual signaling system that authorizes the production or movement of items in Lean is called:", ["Kanban", "Kaizen", "Kobe", "Karate"], 0),
  mc(17, "What is capacity utilization?", ["The percentage of total available design capacity actually being used", "The total storage volume of warehouse shipping crates", "The weight capacity of an overhead crane", "The battery life of electric delivery vans"], 0),
  mc(18, "Which type of layout arranges machines along the sequential path that the product follows during assembly?", ["Product (Assembly Line) Layout", "Process (Functional) Layout", "Fixed-Position Layout", "Random Layout"], 0),
  mc(19, "Shipbuilding and construction of commercial towers typically use which layout?", ["Fixed-Position Layout", "Product Assembly Line", "Continuous Fluid Flow", "Supermarket Merchandising"], 0),
  mc(20, "What is the primary role of an Enterprise Resource Planning (ERP) system?", ["Integrating all core departmental business processes and data into a single system", "Designing computer hardware circuitry", "Managing employee social media accounts", "Encrypting consumer credit card numbers"], 0),
  tf(21, "Quality assurance focuses on preventing defects during the process rather than just inspecting finished products.", true),
  tf(22, "Lead time is the total duration elapsed from placing an order until the goods are received.", true),
  mc(23, "Costs associated with inspecting, testing, and auditing products to ensure quality standards are:", ["Appraisal Costs", "Internal Failure Costs", "External Failure Costs", "Prevention Costs"], 0),
  mc(24, "A process flowchart visually illustrates:", ["The sequence of steps, decision points, and workflows in a process", "The hierarchical organizational tree of executives", "The historical fluctuation of currency exchange rates", "The quarterly sales commission of sales teams"], 0),
  mc(25, "Cross-docking in modern logistics involves:", ["Transferring goods directly from incoming transport to outbound trucks with minimal storage", "Storing goods in ocean containers for six months", "Building retail stores inside sea freight terminals", "Inspecting ships for biological contaminants"], 0),
  mc(26, "The PDCA cycle in continuous improvement stands for:", ["Plan, Do, Check, Act", "Produce, Deliver, Collect, Audit", "Prioritize, Decide, Create, Assess", "Prevent, Document, Correct, Approve"], 0),
  mc(27, "Work-in-Process (WIP) inventory represents:", ["Goods currently undergoing manufacturing that are not yet finished products", "Raw steel stored outside a warehouse", "Packaged goods displayed in grocery stores", "Damaged goods discarded in scrap bins"], 0),
  mc(28, "Preventive maintenance is performed:", ["Regularly on a schedule to prevent unexpected equipment breakdowns", "Only after a machine has completely caught fire or stalled", "When spare factory workers have idle time", "When government safety inspectors arrive unannounced"], 0),
  tf(29, "Takt time represents the pace of production needed to match customer demand pace.", true),
  mc(30, "A Bill of Materials (BOM) is best described as:", ["The complete list of all raw materials, components, and quantities required to build an item", "The customer invoice for an annual equipment warranty", "The building utility bill for electricity and water", "The shipping cargo manifest stamped by customs officials"], 0),
]
