export type Article = {
  slug: string
  title: string
  date: string
  comments: number
  excerpt: string
  content: string
  category: string
  categoryColor: string
  iconName: "users" | "trending-up" | "zap" | "globe"
  image: string
  featured?: boolean
}

export const articles: Article[] = [
  {
    slug: "cpace-san-beda-partnership",
    title: "CPACE Philippines and San Beda University Manila Forge Partnership to Expand Microcredential Opportunities for Students",
    date: "March 18, 2026",
    comments: 0,
    excerpt: "With this collaboration, CPACE Philippines and San Beda University Manila reaffirm their dedication to empowering…",
    content: "CPACE Philippines and San Beda University have officially formalized a strategic partnership through the signing of a Memorandum of Agreement (MOA), marking a significant step toward strengthening industry-academe collaboration.\n\nThe partnership aims to provide San Beda students with enhanced access to globally aligned certification programs and microcredential opportunities. Through this initiative, students will be able to complement their academic degrees with industry-relevant certifications, equipping them with practical skills and competencies demanded in today’s evolving workforce.\n\nThis collaboration underscores both institutions’ shared commitment to bridging the gap between academic learning and real-world application. By integrating CPACE’s professional certification programs into the university ecosystem, students are expected to gain a competitive edge as they prepare to enter their respective industries.\n\nSan Beda University, known for its strong academic foundation and commitment to holistic student development, continues to expand its industry linkages to ensure that graduates are future-ready. Meanwhile, CPACE Philippines continues to broaden its reach across educational institutions, reinforcing its mission to elevate professional standards through accessible and high-quality certification programs.\n\nThe partnership reflects a growing trend among higher education institutions to align closely with industry leaders—ensuring that graduates are not only academically prepared but also equipped with globally competitive credentials.\n\nWith this collaboration, CPACE Philippines and San Beda University Manila reaffirm their dedication to empowering the next generation of professionals through innovation, excellence, and meaningful partnerships.",
    category: "Partnership",
    categoryColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    iconName: "users",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: true,
  },
  {
    slug: "beyond-job-titles",
    title: "Beyond Job Titles: Orchestrating People, Tech, and Purpose",
    date: "February 6, 2026",
    comments: 0,
    excerpt: "We're living in a liminal hour where titles matter less than capability. This piece argues…",
    content: "We're living in a liminal hour where titles matter less than capability. This piece argues that modern organizations must focus on orchestrating people, technology, and purpose as a single ecosystem rather than working in silos.\n\nTo build future-proof teams, organizations need to move away from static job descriptions and embrace a dynamic skill-based architecture. Aligning people's innate talent with technology empowers them to achieve higher productivity and organizational goals.\n\nUltimately, purpose remains the ultimate compass. A strong, shared vision unites teams and ensures technology acts as an enabler rather than a disruptor.",
    category: "Industry Insights",
    categoryColor: "bg-blue-100 text-blue-700 border-blue-200",
    iconName: "trending-up",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    slug: "fintech-revolution-summit-2026",
    title: "Fintech Revolution Summit – Philippines 2026",
    date: "January 26, 2026",
    comments: 0,
    excerpt: "The Fintech Revolution Summit is set to return to Manila on April 30, 2026, at…",
    content: "The Fintech Revolution Summit is set to return to Manila on April 30, 2026, bringing together industry leaders, innovators, and policymakers from across the region.\n\nThe summit will focus on the rapid growth of digital banking, decentralized finance, and blockchain integrations within the Philippine financial sector. Key speakers will address the challenges of cybersecurity, financial inclusion, and the regulatory frameworks required to sustain digital transformation.\n\nAttendees can expect deep-dive panels, networking opportunities, and showcase exhibitions of the latest fintech solutions poised to redefine banking and commerce.",
    category: "Events",
    categoryColor: "bg-violet-100 text-violet-700 border-violet-200",
    iconName: "zap",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    slug: "chro-philippines-2026",
    title: "CHRO Philippines 2026: Navigating the Future of HR in the Philippines",
    date: "December 16, 2025",
    comments: 0,
    excerpt: "CHRO Philippines 2026: Navigating the Future of HR in the Philippines 27–28 January…",
    content: "CHRO Philippines 2026: Navigating the Future of HR in the Philippines will be hosted on January 27–28, 2026. The conference highlights the critical role of human resource leaders in shaping agile and remote-friendly organizational cultures.\n\nTopics will include modern talent acquisition strategies, mental health and wellness in the workplace, and leveraging AI for HR analytics. As the hybrid work model becomes a permanent fixture in the country, HR professionals must acquire new competencies to keep their workforce motivated, collaborative, and highly engaged.\n\nJoin senior executives and industry pioneers to discuss strategies, build networks, and share insights.",
    category: "Events",
    categoryColor: "bg-violet-100 text-violet-700 border-violet-200",
    iconName: "zap",
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    slug: "cpace-gordon-college-cfms",
    title: "CPACE Philippines, Gordon College host CFMS exam among graduating students",
    date: "December 12, 2025",
    comments: 0,
    excerpt: "The CPACE Philippines has partnered with Gordon College to host the CFMS exam among graduating students…",
    content: "The CPACE Philippines has partnered with Gordon College to host the CFMS exam among graduating students, facilitating direct access to professional credentials.\n\nThis initiative bridges the gap between traditional academic curricula and modern business requirements. By enabling graduating seniors to earn the Certificate in Financial Management Services (CFMS) alongside their college degree, the program ensures they enter the job market with validated, high-demand skills.\n\nRepresentatives from both Gordon College and CPACE expressed high expectations for the program's success and its long-term benefits to student employment rates.",
    category: "Partnership",
    categoryColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    iconName: "users",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    slug: "batstateu-cpace-accord",
    title: "BatStateU, CPACE Philippines seal accord to expand students' career growth",
    date: "December 2, 2025",
    comments: 0,
    excerpt: "The CPACE Philippines has signed an accord with BatStateU to expand students' career growth opportunities…",
    content: "The CPACE Philippines has signed an accord with BatStateU to expand students' career growth opportunities through globally aligned credentials.\n\nUnder this agreement, BatStateU will integrate CPACE certification pathways into their business and technology departments. Students will gain first-hand access to specialized materials and exam seats, facilitating credentials that are highly valued by corporate recruiters.\n\nThis partnership reinforces BatStateU's dedication to quality education and future-ready career readiness for all its students.",
    category: "Partnership",
    categoryColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    iconName: "users",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    slug: "nemsu-tagbina-cpace-collab",
    title: "NEMSU Tagbina in Mindanao to collab with CPACE Philippines after fruitful first CFMS® exam",
    date: "November 28, 2025",
    comments: 0,
    excerpt: "A fruitful first CFMS® exam paves the way for a lasting collaboration between NEMSU Tagbina and CPACE Philippines…",
    content: "A fruitful first CFMS® exam paves the way for a lasting collaboration between NEMSU Tagbina and CPACE Philippines, extending professional education to Mindanao.\n\nFollowing the outstanding performance of NEMSU Tagbina students in the recent CFMS exam, both organizations have agreed to establish a continuous framework for certification hosting and training.\n\nThis milestone represents a major step forward in making premium professional training accessible to students and instructors in regional educational hubs.",
    category: "Partnership",
    categoryColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    iconName: "users",
    image: "https://images.unsplash.com/photo-1577896851231-70ef18881754?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    slug: "stop-forwarding-emails",
    title: "Stop Forwarding Emails: How cloudHQ Gmail Label Sharing Syncs Your Entire Team",
    date: "November 25, 2025",
    comments: 0,
    excerpt: "In the modern workplace, email remains a cornerstone of communication. cloudHQ's Gmail Label Sharing changes the game…",
    content: "In the modern workplace, email remains a cornerstone of communication, but forwarding threads can quickly lead to version confusion and lost context. cloudHQ's Gmail Label Sharing changes the game by syncronizing entire labels between team members in real-time.\n\nBy sharing a Gmail label, any email sorted into that label automatically appears in your team's folders. This eliminates redundant forwards, speeds up client communication, and ensures all team members have access to up-to-date communication logs without leaving their preferred email client.\n\nDiscover how this tech can streamline collaboration and save hours of administrative overhead every week.",
    category: "Technology",
    categoryColor: "bg-orange-100 text-orange-700 border-orange-200",
    iconName: "globe",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    slug: "cpace-wlc-partnership",
    title: "CPACE Philippines, WLC Partner to Future-Proof Financial Mgmt Curriculum",
    date: "November 21, 2025",
    comments: 0,
    excerpt: "The CPACE Philippines has officially signed a partnership with WLC to future-proof the Financial Management curriculum…",
    content: "The CPACE Philippines has officially signed a partnership with WLC to future-proof the Financial Management curriculum with industry-relevant skills.\n\nThe collaboration introduces certified course modules that align with current international practices in corporate finance, budgeting, and risk analysis. By blending theory with practice, WLC students will graduate with the practical tools and credentials needed to excel in competitive finance sectors.\n\nBoth institutions aim to raise the bar for financial education and support local businesses with highly competent finance professionals.",
    category: "Partnership",
    categoryColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    iconName: "users",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
]
